language:
os: linux
dist: xenial
compiler: gcc
addons: 
  apt:
    packages:
      - bmake
before_install:
  - "mkdir libcheck"
  - "wget https://github.com/libcheck/check/releases/download/0.12.0/check-0.12.0.tar.gz -O - | tar -xvz"
  - "pushd check-0.12.0; PREFIX=/usr ./configure; make; sudo make install; popd"

script:
  - cd src && bmake check && ./check
